version: '3'

services:
  web:
    build: ./
    image: java-demo:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend.loadbalancer.sticky=true"
      - "traefik.backend=java-demo"
      - "traefik.frontend.rule=Host:java-demo.sbs.guj.de"

networks:
  web:
    external:
      name: traefik_webgateway
