version: '3'

services:
  proxy:
    image: traefik
    command: --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker --docker.domain=sbs.guj.de --docker.endpoint=unix://var/run/docker.sock --docker.exposedbydefault=false --logLevel=DEBUG --web.certfile="/wildcard_sbs_guj_de_traefik.crt" --web.keyfile="/wildcard_sbs_guj_de.key"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8443:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./wildcard_sbs_guj_de_traefik.crt:/wildcard_sbs_guj_de_traefik.crt
      - ./wildcard_sbs_guj_de.key:/wildcard_sbs_guj_de.key
    deploy:
      labels:
        - "traefik.enable=false"
        - "traefik.frontend.rule=Host:{service}.{domain}"

networks:
  webgateway:
    driver: bridge
