version: '3'

services:
  proxy:
    image: traefik
    #command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    command: --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker --docker.domain=localdomain --docker.endpoint=unix://var/run/docker.sock --docker.exposedbydefault=false --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      labels:
        - "traefik.enable=false"
        - "traefik.frontend.rule=Host:{service}.{domain}"

networks:
  webgateway:
    driver: bridge
